### ISSUE TITLE
Backtracking mutator and forced index sorting

### ISSUE THREAD

**Issue by botev** [bluss/petgraph#115]
Is it possible to implement an iterator (topological) over the graph from another crate which does smth along the lines:

1. Find node matching some criteria
2. Remove/Modify the node, and its neghbours (potentially replace it with a new node)
3. Rather than advancing put on the next nodes to be firstly all affected nodes then advance

Also, wondering if it would be possible to be able to reorder the graph's indices, such that we can achieve a topological sorting, but with extra constraints, or if it is possible to force to change the indices based on topological order or other provided ordering.

**Comment by bluss** [comment]
In general the petgraph::Graph structure does not lend itself well to being updated during use. It's more appropriate for building a new graph while reading an old one.

I think it's possible to change node indices like that, but it's a large operation. What I would forsee is an operation that takes a graph, a mapping from old indices to new indices, and produces a new graph with the new indices.

**Comment by botev** [comment]
Hmm, just to explain the use case and maybe you would be able to point me out if is achievable with petgraph (or you might have better suggestions how to do this). Just Note I use Rust for a few weeks so my view is very beginnerish. 

I want to build a small compiler, similar to LLVM, which uses an SSA representation. I can write my own graph, but I wanted to potentially reuse the petgraph exactly for the SSA bit. Now when we get to the optimization part there are many local optimizations that can be applied, such as merging expressions, removing unneeded ones etc... The interface of writing this would most likely be something like a Walker where you apply X if you meet some conditions. The problem is that you can have 30-50 such micro optimizations, but they are affecting only local structure in the graph. They are also rotatingly applicable, in the sense You migtht not be able to apply X now, but you apply first Y, then the modification leads to X being possible. Rather than traversing the graph many times until no change we want to be able to change small bits of the graph and then continue only from the bits that have been affected, saving significant time in scanning to trough the graph again.

**Comment by bluss** [comment]
Good question. I don't think rustc has solved this one either..

Does it fit to use StableGraph? Since it allows removing out nodes/edges without disturbing any indices. Like StableGraph’s docs say, it needs contributions/feedback to bring it up to parity with Graph.

I don't immediately see a way of how to do the relabeling to create a local graph. Maybe it's possible to introduce a virtual local root and shadow edges, and use them to knit together the local graph.

If it proves efficient to do so, we could try to write a new feature for StableGraph that takes a subgraph (specified somehow) and moves it all to the end of the index order. To the end, because then there is a lower bound and one can iterate from the lower bound towards the end repeatedly. (The end of the index order is where new nodes are added.)

**Comment by bluss** [comment]
This issue was used for discussion
