### ISSUE TITLE
add methods for adding a node or edge to the graph and returning a reference

### ISSUE THREAD

**Issue by generalelectrix** [bluss/petgraph#121]
It would be useful if graphs exposed methods that add a node/edge and return both the index for that node/edge as well as a immutable or mutable reference to the node/edge weight.  I keep running into the unfortunate pattern of
```rust
let idx = g.add_node(node_weight);
let node = g.node_weight(idx).unwrap();
```
which adds a smelly "I know that this unwrap can't fail" unwrap.

**Comment by bluss** [comment]
A note is that `g.node_weight(idx).unwrap()` is equivalent to `&g[idx]`.

**Comment by jmcomets** [comment]
I don't think this would be useful. Returning a reference to the node/edge's weight would ruin usability, because the following would no longer compile:

```rust

let mut g = Graph::new();
let wa = g.add_node("a", 42);
let wb = g.add_node("b", 1337); // won't compile because `wa` borrows `g`
```

Node IDs for `Graph` are direct accessors and bypass Rust's BCK and using them incorrectly is expected to panic. You can think of it like using `Vec` indices instead of references to elements.

```rust

fn add_to_vec<T>(v: &mut Vec<T>, element: T) -> usize {
    v.push(element);
    v.len()
}

fn main() {
    let mut v = vec!["a", "b", "c"];
    
    let d = add_to_vec(&mut v, "d");
    v[d] = "D";

    let ref_d = &v[d];
    let e = add_to_vec(&mut v, "e"); // doesn't compile
}

```

**Comment by generalelectrix** [comment]
I wasn't suggesting that add_node return a reference, rather to expose a different variant that does.  Not really necessary, just convenient, but it would imply more API surface for not a lot of gain.
