### ISSUE TITLE
astar algorithm

### ISSUE THREAD

**Issue by Dushistov** [bluss/petgraph#138]
It would be nice to have  [A*](https://en.wikipedia.org/wiki/A*_search_algorithm) implementation in petgraph library. For path finding and similar stuff.

**Comment by jmcomets** [comment]
I can look into this, I've written quite a few A* implementations before. The usage should be pretty close to the `Dijkstra` API, and will probably have the same requirements.

**Comment by niclashoyer** [comment]
I just discovered https://github.com/samueltardieu/pathfinding while searching for an A* implementation for petgraph.

Would it be possible to join/align with the pathfinding crate? Or are implementations on petgraph more efficient?

**Comment by niclashoyer** [comment]
great! 🎢 🎈

**Comment by bluss** [comment]
As one might have seen I wasn't so good at answering any questions during summer and before. To answer is that I don't know their library so well, but their implementation is generic in graph types and our is, so it should be dependent on the graph type alone. I see they have some simple ad hoc formats which are surely more efficient since they are more compact.
