### ISSUE TITLE
bellman_ford does not handle Undirected graphs correctly

### ISSUE THREAD

**Issue by carrutstick** [bluss/petgraph#150]
`bellman_ford` fails when called on certain nodes in an undirected graph:
```
extern crate petgraph;
use petgraph::prelude::*;
use petgraph::algo;
fn main() {
    let mut graph: GraphMap<usize, f32, Undirected> = GraphMap::new();
    graph.add_edge(0, 1, 1f32);
    algo::bellman_ford(&graph, 1).unwrap();
}
```

```
> cargo run
   Compiling pgtest v0.1.0 (file:///home/***************)
    Finished dev [unoptimized + debuginfo] target(s) in 0.78 secs
     Running `target/debug/pgtest`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NegativeCycle(())', /checkout/src/libcore/result.rs:859
```

This is because `bellman_ford` uses `Graph::edge_references` in the main pass of the algorithm, and so treats undirected edges as though they had a single direction. This leaves nodes that should be reachable marked as unreachable. In the test pass of the algorithm, the function uses `Graph::edges`, which correctly checks the edges in both directions, but incorrectly assumes it has found a negative cycle when it then visits a node previously thought to be unreachable.

I believe one of two things needs to change to fix this:
 1.  `edge_references` should return edges in both forward and backward directions (when called on an undirected graph), or
 2. `bellman_ford` needs some way of checking whether `G` is `Directed` or `Undirected`.

I'm not particularly familiar with this project, so I don't know how feasible the potential solutions are.

**Comment by bluss** [comment]
Thanks for reporting this issue.

**Comment by carrutstick** [comment]
I'm happy to help with a solution if you know what direction you want to take it.

**Comment by bluss** [comment]
Well we have the GraphProp trait which covers the kind of edges the graph has.

Undirected graphs came up with Bellman–Ford once already, but that was about a negatively weighted edge and we simply have to say that if the graph is undirected, it's the same as having edges both way, so that's a negative cycle. So that issue is settled. That said, the algorithm should work fine with strictly positive edges in undirected graphs. But is it a good idea to use it?

I think we should fix the algorithm to check the graph directionality and adapt accordingly. Unless any problem is found in implementation.

What to do about edge_references is a more complicated question. I don't think it is wrong as it is, an undirected graph doesn't have twice the edges, only if trying to translate it to a digraph, which isn't always what you want to do.
