### ISSUE TITLE
Allow user to specify indices for nodes?

### ISSUE THREAD

**Issue by AGausmann** [bluss/petgraph#186]
The way that graph indexing works right now seems a bit odd. `add_node()` returns a `NodeIndex` object generated by the graph that is used to later reference that node. The issue is that I already have indices ([see the details here](https://www.reddit.com/r/dailyprogrammer/comments/7c4bju/20171110_challenge_339_hard_severing_the_power/)) for my nodes. The solution right now is to create a `Map` outside of the graph to map my indices to the internal indexing system.

Several well-known graph libraries in other languages (for example:,[networkx](https://networkx.github.io/documentation/stable/reference/introduction.html#graph-creation) and [igraph](http://igraph.org/c/doc/igraph-Basic.html)) enable custom indexing out of the box; it would be nice to see this implemented in petgraph as well. It would make the interface easier to use and keep end-user code much cleaner.

**Comment by bluss** [comment]
It's a bit lower level this way maybe. Graph and StableGraph will not change, they are what they are.

My perspective is that

- We want to improve GraphMap, possibly reimplement it so that it comes closer to what you describe while also coming closer to `Graph`
- If not that, so maybe a separate GraphBuilder that keeps a map in a building phase for a graph (this is something I've used in an own projects, but there's no published one)
- With enough imagination and rust-how maybe there's a good way to make it an add-on to an existing graph type (including Graph, StableGraph), without changing those two types themselves. We don't have that much leeway to play with wrappers here like we could do in Python.

**Comment by bluss** [comment]
We can certainly discuss it more (no closure on that front), but the issue is not actionable as it is.
