### ISSUE TITLE
Parallel iteration on immutabe node references

### ISSUE THREAD

**Issue by sanmai-NL** [bluss/petgraph#198]
Would it be possible to implement to [`IntoParallelIterator`](https://docs.rs/rayon/0.9.0/rayon/iter/trait.IntoParallelIterator.html) for [`stable_graph::NodeReferences`](https://docs.rs/petgraph/0.4.11/petgraph/stable_graph/struct.NodeReferences.html)? 

There was previous discussion of implementing mutable access to the raw `Node` collection in #117; in the end that was put off. Is there a particular stumbling block to implementing the immutable [`raw_nodes()`](https://docs.rs/petgraph/0.4.11/petgraph/graph/struct.Graph.html#method.raw_nodes) for `StableGraph`, as it was for `Graph`?

**Comment by bluss** [comment]
I don't know about `IntoParallelIterator` for that stable graph iterator -- it is not an `ExactSizeIterator`, it doesn't have simple random access split, so it doesn't seem like a good candidate. Basically a collect-to-vec solution or parallel iterator for the index range (covering 0 to upper bound) is the best.

And yes, the path is closed. The design is as follows:

* `Graph` is nakedly confessing it is a `Vec<Node<..>>` and a `Vec<Edge<..>>` and it has some "low level" accessors to the details of the data structure, because it is simple. Yet it does not expose mutable versions of all that so that its invariants can not be harmed.
* `StableGraph` has a more complicated implementation and will not expose any low level details, that would harm its encapsulation.
