### ISSUE TITLE
Expose basic memory management methods in Graph's API

### ISSUE THREAD

**Issue by fuine** [bluss/petgraph#73]
Hi,
I'm implementing genome assembler using `petgraph`, and i really miss functions that would allow me to actively change `Graph`'s capacity:

- `shrink_to_fit_nodes()`
- `shrink_to_fit_edges()`
- `reserve_nodes(usize)`
- `reserve_edges(usize)`

Often i find myself in the situation in which `Graph`'s capacity is orders of magnitude higher than what i'm actually storing in the graph (it happens when huge graph is getting aggressively pruned).
Likewise when i create such huge graphs i would like to have some control over allocation sizes, hence `reserve`s. 
Are there any specific reasons why these methods aren't available in the current API (as they are available in the underlying Vecs)? I would gladly implement these methods if you agreed on merging them.

Thanks for this awesome crate!

**Comment by bluss** [comment]
Thank you for the feedback! These are fine to add, I didn't think they were needed. I mostly create new graphs when pruning. (Removing existing nodes/edges is a bit hairy isn't it, not the best data structure for that).

Since it's still summer here, I may be a bit slow to respond but a PR is welcome.
